CREATE TABLE funcionarios (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    administrador BIT NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    nome VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL
);